# Clock signal 
set_property PACKAGE_PIN W5 [get_ports clk]  	 	 	 	  
 	set_property IOSTANDARD LVCMOS33 [get_ports clk] 
create_clock -add -name sys_clk_pin -period 10.00 -waveform {0 5} [get_ports clk] 



# Switches
set_property PACKAGE_PIN V17 [get_ports {adress[0]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {adress[0]}]
set_property PACKAGE_PIN V16 [get_ports {adress[1]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {adress[1]}]
set_property PACKAGE_PIN W16 [get_ports {adress[2]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {adress[2]}]
set_property PACKAGE_PIN W17 [get_ports {adress[3]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {adress[3]}]

set_property PACKAGE_PIN V2 [get_ports {sw[0]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {sw[0]}]
set_property PACKAGE_PIN T3 [get_ports {sw[1]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {sw[1]}]
set_property PACKAGE_PIN T2 [get_ports {sw[2]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {sw[2]}]
set_property PACKAGE_PIN R3 [get_ports {sw[3]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {sw[3]}]
set_property PACKAGE_PIN W2 [get_ports {sw[4]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {sw[4]}]
set_property PACKAGE_PIN U1 [get_ports {sw[5]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {sw[5]}]
set_property PACKAGE_PIN T1 [get_ports {sw[6]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {sw[6]}]
set_property PACKAGE_PIN R2 [get_ports {sw[7]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {sw[7]}]
	
# LEDs
set_property PACKAGE_PIN U16 [get_ports {led_adress[0]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {led_adress[0]}]
set_property PACKAGE_PIN E19 [get_ports {led_adress[1]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {led_adress[1]}]
set_property PACKAGE_PIN U19 [get_ports {led_adress[2]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {led_adress[2]}]
set_property PACKAGE_PIN V19 [get_ports {led_adress[3]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {led_adress[3]}]
set_property PACKAGE_PIN V13 [get_ports {led_data[0]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {led_data[0]}]
set_property PACKAGE_PIN V3 [get_ports {led_data[1]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {led_data[1]}]
set_property PACKAGE_PIN W3 [get_ports {led_data[2]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {led_data[2]}]
set_property PACKAGE_PIN U3 [get_ports {led_data[3]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {led_data[3]}]
set_property PACKAGE_PIN P3 [get_ports {led_data[4]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {led_data[4]}]
set_property PACKAGE_PIN N3 [get_ports {led_data[5]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {led_data[5]}]
set_property PACKAGE_PIN P1 [get_ports {led_data[6]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {led_data[6]}]
set_property PACKAGE_PIN L1 [get_ports {led_data[7]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {led_data[7]}]
	
	
##7 segment display
set_property PACKAGE_PIN W7 [get_ports {seg[0]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {seg[0]}]
set_property PACKAGE_PIN W6 [get_ports {seg[1]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {seg[1]}]
set_property PACKAGE_PIN U8 [get_ports {seg[2]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {seg[2]}]
set_property PACKAGE_PIN V8 [get_ports {seg[3]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {seg[3]}]
set_property PACKAGE_PIN U5 [get_ports {seg[4]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {seg[4]}]
set_property PACKAGE_PIN V5 [get_ports {seg[5]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {seg[5]}]
set_property PACKAGE_PIN U7 [get_ports {seg[6]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {seg[6]}]
set_property PACKAGE_PIN V7 [get_ports {seg[7]}]							
	set_property IOSTANDARD LVCMOS33 [get_ports {seg[7]}]

set_property PACKAGE_PIN U2 [get_ports {an[0]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {an[0]}]
set_property PACKAGE_PIN U4 [get_ports {an[1]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {an[1]}]
set_property PACKAGE_PIN V4 [get_ports {an[2]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {an[2]}]
set_property PACKAGE_PIN W4 [get_ports {an[3]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {an[3]}]
	 
	 # Buttons 
set_property PACKAGE_PIN T18 [get_ports btnEnter]                           
     set_property IOSTANDARD LVCMOS33 [get_ports btnEnter] 
set_property PACKAGE_PIN W19 [get_ports btnNext]                           
     set_property IOSTANDARD LVCMOS33 [get_ports btnNext] 
set_property PACKAGE_PIN T17 [get_ports btnPrev]                           
     set_property IOSTANDARD LVCMOS33 [get_ports btnPrev] 
set_property PACKAGE_PIN U17 [get_ports btnDisplay]                           
     set_property IOSTANDARD LVCMOS33 [get_ports btnDisplay] 
set_property PACKAGE_PIN U18 [get_ports btnSum]                           
     set_property IOSTANDARD LVCMOS33 [get_ports btnSum] 